### ISSUE TITLE
Needs xfonts-75dpi installed

### ISSUE THREAD

**Issue by FrankSchouenberg** [thite/wkhtml_0.0.12.5-dev#1]
Can't install due to missing xfonts-75dpi
Installed it manually, but still not working.
After installation of Yenthe666/InstallScript had to remove the symbolic links manually to be sure to make new ones. Unfortunately still not working

**Comment by thite** [comment]
You need to use "sudo apt-get install -f"
It installed all the dependencies on my system.
However, you can now use wkhtmltopdf from original source. Go through -[This link on odoo.com](https://www.odoo.com/forum/help-1/question/ubuntu-18-04-lts-how-to-install-wkhtmltopdf-0-12-1-134198)
Commands to execute:
sudo wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo apt-get install -f
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin

After a service reboot or server reboot it'll work.
